#
# Engine ruleset that defines the order of execution.
#
# This SHOULD NOT be modified unless there is a new set of
# attributes that require different behavior.
#
execute:
  ao: [
    /remove/pre_process/ao,
    /mapping/ao,
    /mapping_user_dn/ao,
    /rules/ao,
    /share_mapping/ao,
    /combine_coi_and_ctrls/ao,
    /lineage/ao,
    /flatten/ao,
    /remove/post_process/ao
  ]
  acm: [
    /remove/pre_process/acm,
    /mapping/acm,
    /rules/acm,
    /share_mapping/acm,
    /combine_coi_and_ctrls/acm,
    /lineage/acm,
    /flatten/acm,
    /validate/acm,
    /remove/post_process/acm
  ]

#
# Resolved values & class implementation definition should go.
resolved_values:
  sci:
    path: /data/sci
    class: gov.ic.dodiis.enterprise.security.policy.mapper.resolve.values.ResolveValuesSci
  mac:
    path: /data/mac
    class: gov.ic.dodiis.enterprise.security.policy.mapper.resolve.values.ResolveValuesCoiAndCtrls
  accm:
    path: /data/accm
    class: gov.ic.dodiis.enterprise.security.policy.mapper.resolve.values.ResolveValuesCoiAndCtrls

validate:
  acm:
    sci:
      source:
        f_sci_ctrls : [ /resolved_values/sci ]
    accm:
      source:
        f_accms : [ /resolved_values/accm ]
    mac:
      source:
        f_macs : [ /resolved_values/mac ]
    unknown_values:
      source:
        tmp_assigned_controls : [ ]
    sar:
      source:
        f_sar_id : [ ]
    aea:
      source:
        f_atom_energy : [ ]

remove:
  pre_process:
    ao:
      attributes: [ /nAccms, /nShare, /nMacs, /nFormalAccess, /f_share, /f_accms, /f_macs, /f_missions, /f_regions, /f_oc_org, /f_clearance, /f_sci_ctrls ]
    acm:
      attributes: [ /f_share, /f_accms, /f_macs, /f_missions, /f_regions, /f_oc_org, /f_clearance, /f_sci_ctrls ]
  post_process:
    ao:
      attributes: [ /tmp_clearance, /tmp_sci_ctrls, /tmp_orgs, /tmp_missions, /tmp_regions, /tmp_accms, /tmp_macs, /tmp_share, /tmp_ignore, /tmp_nFormalAccess, /tmp_user_dn_share ]
    acm:
      attributes: [ /tmp_clearance, /tmp_sci_ctrls, /tmp_orgs, /tmp_missions, /tmp_regions, /tmp_accms, /tmp_macs, /tmp_share, /tmp_ignore, /tmp_atom_energy, /tmp_sar, /assigned_controls, /tmp_assigned_controls, /tmp_processed_assigned_controls ]

#
# This is an engine ruleset that you do not have to update unless
# there is a new attribute that is leveraging coi and coi_ctrls.
#
combine_coi_and_ctrls:
  ao:
    accm:
      - def:
          source:
            expression: (/nAccms[1]!='')
          destination:
            normalized:
              - value:
                  tmp_accms: [ /nAccms ]
    mac:
      - def:
          source:
            expression: (/nMacs[1]!='')
          destination:
            normalized:
              - value:
                  tmp_macs: [ /nMacs ]
  acm:
    accm:
      - def:
          source:
            expression: (/accms[1]!='')
          destination:
            normalized:
              - value:
                  tmp_accms: [ /accms ]
    mac:
      - def:
          source:
            expression: (/macs[1]!='')
          destination:
            normalized:
              - value:
                  tmp_macs: [ /macs ]

#
# This is an engine rulset that you do not have to update unless
# there are new attributes that will be used to generate
# share data.
#
share_mapping:
  ao:
    share:
      - def:
          source:
            path: /localUserGroups/projects
          destination:
            normalized:
              - value:
                  nShare: { /@projectName : [ /@groupNames ] }
      - def:
          source:
             path: (/diasUserGroups/projects[@projectName!='Focal Point'][@projectName!='RMT'])
          destination:
            normalized:
              - value:
                  nShare: { /@projectName : [ /@groupNames ] }
    combine:
      - def:
          source:
            expression: (/nShare[1]!='')
          destination:
            normalized:
              - value:
                  tmp_share: [ /nShare ]
  acm:
    combine:
      - def:
          source:
            expression: (/share/users[1]!='')
          destination:
            normalized:
              - value:
                  tmp_share: [ /share/users ]
      - def:
          source:
            expression: (/share/projects[1]!='')
          destination:
            normalized:
              - value:
                  tmp_share: [ /share/projects ]